from app.tools.datatools import load_csv
from app.tools.mltools import train_model


def execute(file, tasks):
    """
    Executes tasks generated by the planner.
    """

    df = None
    result = None

    for task in tasks:

        if task["task"] == "load_data":
            df = load_csv(file)

        elif task["task"] == "preprocess_data":
            # Placeholder
            pass

        elif task["task"] == "train_models":
            target_col = df.columns[-1]
            result = train_model(df, target_col)

        elif task["task"] == "evaluate_model":
            # Already handled inside train_model()
            pass

        elif task["task"] == "save_model":
            # Already handled inside train_model()
            pass

        elif task["task"] == "generate_report":
            # Already included in train_model()
            pass

        task["status"] = "completed"

    return {
        "tasks": tasks,
        "result": result
    }